const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const artDir = path.join(__dirname, '../public/art');
const outFile = path.join(__dirname, '../src/data/artVersions.js');

function hashFile(filePath) {
  const buf = fs.readFileSync(filePath);
  return crypto.createHash('md5').update(buf).digest('hex').slice(0, 10);
}

function main() {
  if (!fs.existsSync(artDir)) {
    fs.writeFileSync(outFile, 'export const ART_VERSIONS = {};\n');
    return;
  }

  const versions = {};
  const files = fs.readdirSync(artDir).filter((f) => /\.(jpe?g|png|webp|gif)$/i.test(f));

  for (const file of files.sort()) {
    const full = path.join(artDir, file);
    if (!fs.statSync(full).isFile()) continue;
    versions[`/art/${file}`] = hashFile(full);
  }

  const body = `// Auto-generated by scripts/hash-art.js — do not edit\nexport const ART_VERSIONS = ${JSON.stringify(versions, null, 2)};\n`;
  fs.writeFileSync(outFile, body);
  console.log(`Hashed ${files.length} art file(s) → src/data/artVersions.js`);
}

main();
